GET http://localhost:8080/api/racas-caes

###

POST http://localhost:8080/api/racas-caes
Content-Type: application/json

{
    "raca":"golden",
    "tamanho": 40,
    "paisOrigem": "Brasil",
    "pesoMedio": 12
}
